export const dugamSEOData = {
  brandName: "Dugam (Mera Dukan Mera Godam)",
  siteUrl: "https://www.dugam.in",
  pricing: {
    monthly: "₹99/month",
    yearly: "₹999/year",
    daily: "₹2.74/day",
    yearlyHook: "Sirf ₹2.74/din me poori dukan aur godam manage karein",
  },
  appDescription:
    "Dugam is an affordable inventory management and GST billing app for Indian MSMEs, kirana stores, wholesalers, retailers, and small business teams.",
  primaryKeywords: [
    "inventory management software",
    "stock management software",
    "inventory software india",
    "warehouse management software",
    "godown management software",
    "shop management software",
    "retail management software",
    "GST billing software",
    "GST invoice software",
    "GST bill generator",
    "GST bill maker",
    "billing software india",
    "retail billing software",
    "invoice software india",
    "stock inventory tracker",
    "inventory tracker app",
    "purchase management software",
    "sales management software",
    "expense management software",
    "POS software india",
    "retail POS software",
    "inventory management app",
    "stock management app",
    "free inventory software",
    "free GST billing software",
  ],
  businessKeywords: [
    "kirana store software",
    "grocery shop billing software",
    "hardware shop billing software",
    "electronics shop billing software",
    "mobile shop inventory software",
    "medical store inventory software",
    "pharmacy billing software",
    "garment shop billing software",
    "footwear shop inventory software",
    "stationery shop billing software",
    "wholesale inventory software",
    "distributor inventory software",
    "supermarket inventory software",
  ],
  pricingKeywords: [
    "billing software under 1000 rupees",
    "inventory software under 999 rupees",
    "affordable GST billing software",
    "budget inventory management software",
    "billing software for small business",
    "inventory software for MSME",
    "billing software under 100 rupees per month",
    "GST software for small shops",
  ],
  competitorKeywords: [
    "Vyapar alternative",
    "TallyPrime alternative",
    "myBillBook alternative",
    "Swipe alternative",
    "Busy Accounting alternative",
    "Marg ERP alternative",
    "Zoho Inventory alternative",
    "QuickBooks alternative",
    "Khatabook alternative",
  ],
} as const
